### ISSUE TITLE
extension is not available in the repository

### ISSUE THREAD

**Issue by mykhaylo-** [georgringer/page_speed#8]
Hi Georg,
Seems to be a pretty useful extension but it is not available in the extension repository.
![image](https://user-images.githubusercontent.com/3473564/53259008-ade6dc00-36d6-11e9-95c2-66487f058987.png)
Do you plan to publish it or it has to be downloaded from github and installed manually?
Thanks

**Comment by mykhaylo-** [comment]
Actually it is available but only for typo3 v.7
![image](https://user-images.githubusercontent.com/3473564/53259145-0ae29200-36d7-11e9-8b6a-e958963c8e76.png)
while in your ext_emconf I see typo3 version 9. So do you have any idea why typo3 extensions site shows an outdated version of the extension?

**Comment by georgringer** [comment]
I didn't release to ter

**Comment by mykhaylo-** [comment]
So what is the best way to get it to my site then? Just clone repository or there are some alternative ways?

**Comment by georgringer** [comment]
use composer but otherwise, yes clone
